name: napari-env
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=1.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - app-model=0.4.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bermuda=0.1.6=py310h53169e7_1
  - blas=1.0=openblas
  - bokeh=3.8.0=py310hca03da5_0
  - bottleneck=1.4.2=py310hbda83bc_0
  - brotli-python=1.1.0=py310h1af2607_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - cfgv=3.3.1=pyhd8ed1ab_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=1.1.0=py310hfe3a0ae_1
  - dask-core=2025.10.0=pyhcf101f3_0
  - debugpy=1.8.17=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fasteners=0.19=pyhd8ed1ab_1
  - filelock=3.20.0=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - freetype-py=2.5.1=pyhd8ed1ab_1
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - glib=2.84.0=heee381b_0
  - glib-tools=2.84.0=h1dc7a0c_0
  - gst-plugins-base=1.22.9=h09b4b5e_1
  - gstreamer=1.22.9=h551c6ff_1
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=py310h2232773_0
  - hdf5=1.14.5=hd77251f_2
  - heapdict=1.0.1=pyhd8ed1ab_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hsluv=5.0.4=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h6b3803e_0
  - identify=2.6.15=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=py310hca03da5_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - in-n-out=0.2.1=pyhd8ed1ab_1
  - ipykernel=6.31.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310hca03da5_0
  - joblib=1.5.2=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.8=py310h313beb8_0
  - krb5=1.20.1=h69eda48_0
  - lazy_loader=0.4=py310hca03da5_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libclang=14.0.6=default_h5dc8d65_1
  - libclang13=14.0.6=default_hc7183e1_1
  - libcurl=8.15.0=hcdd2897_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.0=hdff4504_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libllvm14=14.0.6=hd1a9a77_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=hf2bb037_0
  - libopenjpeg=2.5.4=haa24f5a_0
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h5c318fc_0
  - libpq=15.3=h7126958_1
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.0=h91aec0a_0
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.3.2=h80987f9_1
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.44.0=py310heb35c27_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h313beb8_1
  - magicgui=0.10.1=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib=3.10.6=py310hca03da5_0
  - matplotlib-base=3.10.6=py310h066045a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py310h062c92d_0
  - mpich=4.1.1=he2630cc_0
  - msgpack-python=1.1.2=py310h0e897d2_0
  - mysql-common=8.0.33=hf9e6398_6
  - mysql-libs=8.0.33=he3dca8b_6
  - napari=0.6.6=pyh4da3b27_0
  - napari-base=0.6.6=pyhcf101f3_0
  - napari-console=0.1.4=pyhc04f84c_0
  - napari-plugin-engine=0.2.0=pyha07c04f_3
  - napari-plugin-manager=0.1.7=pyha44d970_0
  - napari-svg=0.2.1=pyha07c04f_0
  - narwhals=2.7.0=py310hca03da5_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py310hca03da5_0
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - npe2=0.7.9=pyhd8ed1ab_0
  - nspr=4.37=h31e89c2_0
  - nss=3.117=h1c710a3_0
  - numba=0.61.2=py310h32e2601_0
  - numcodecs=0.13.1=py310h3420790_0
  - numexpr=2.11.0=py310h8c72970_1
  - numpy=1.26.4=py310h901140f_1
  - numpy-base=1.26.4=py310hae06d03_1
  - numpydoc=1.9.0=pyhe01879c_1
  - openjpeg=2.5.4=h959fc53_0
  - openssl=3.1.8=h81ee809_0
  - packaging=25.0=py310hca03da5_1
  - pandas=2.3.3=py310hc6ded6b_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - partsegcore-compiled-backend=0.15.14=py310h25f4b65_1
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h41ba818_1
  - pint=0.24.4=pyhe01879c_2
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.3.0=py310hd096484_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_3
  - pre-commit=4.4.0=pyha770c72_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py310hfe3a0ae_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pydantic-core=2.41.4=py310hf3301a5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=py310hca03da5_0
  - pyopengl=3.1.10=pyh534df25_2
  - pyparsing=3.2.0=py310hca03da5_0
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyqt=5.15.9=py310h2924129_5
  - pyqt5-sip=12.12.2=py310h1253130_5
  - pyqtgraph=0.13.7=py310hca03da5_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.13=h2469fbe_0_cpython
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=py310hca03da5_0
  - pywavelets=1.8.0=py310h80987f9_0
  - pywin32=311=py310h15b4e53_1
  - pyyaml=6.0.2=py310h80987f9_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - qt-main=5.15.8=hfe8d25c_6
  - qtawesome=1.4.0=py310hca03da5_0
  - qtconsole-base=5.7.0=pyha770c72_0
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.28.0=py310hf3301a5_1
  - scikit-image=0.25.2=py310h6e33161_0
  - scikit-learn=1.7.2=py310hc6ded6b_0
  - scipy=1.15.3=py310h132fc3c_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.14.0=py310hc7786af_0
  - six=1.17.0=py310hca03da5_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.6=pyhb6d5dde_0
  - tbb=2021.8.0=h48ca7d4_0
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tifffile=2025.2.18=py310hca03da5_0
  - tk=8.6.13=h892fb3f_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.3.0=pyhcf101f3_0
  - tomli-w=1.2.0=pyhd8ed1ab_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.1=py310h80987f9_0
  - tqdm=4.67.1=py310h33ce5c2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ukkonen=1.0.1=py310hc9b05e5_6
  - umap-learn=0.5.3=py310hca03da5_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - vispy=0.15.2=py310h63f10e6_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=2.0.0=py310hfe3a0ae_0
  - xyzservices=2025.4.0=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zarr=2.18.3=pyhd8ed1ab_1
  - zeromq=4.3.5=hebf3989_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py310hf151d32_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - napari-musa==1.0.0
      - psygnal==0.15.0
      - pybaselines==1.2.1
      - pysptools==0.15.0
      - qtpy==2.4.3
      - spectral==0.24
prefix: /opt/anaconda3/envs/napari-env
